name: Delivery

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git tag --list --sort=-v:refname | head -n1)
          echo "latest=$latest_tag" >> $GITHUB_OUTPUT

      - name: Generate pre-release tag
        id: prerelease
        run: |
          base_version=$(echo "${{ steps.get_tag.outputs.latest }}" | sed 's/-.*//')
          prerelease_base="${base_version}-pre"
          existing=$(git tag --list | grep "${prerelease_base}.*" | wc -l)
          
          if [[ $existing -eq 0 ]]; then
            IFS='.' read -r major minor patch <<< "$(echo "$base_version" | sed 's/^v//')" 
            new_tag="v$major.$minor.$((patch+1))-pre-0"
          else
            new_tag="${prerelease_base}-$((existing))"
          fi
          
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

#      - name: Create pre-release tag
#        run: |
#          git tag "${{ steps.prerelease.outputs.new_tag }}"
#          git push origin "${{ steps.prerelease.outputs.new_tag }}"