name: Delivery

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag information
        id: get_tag_info
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: main
          default_prerelease_bump: false
          default_bump: false
          append_to_pre_release_tag: pre
          tag_prefix: v
          dry_run: 'true'

#      - name: Create new pre-release tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v6.2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          pre_release_branches: main
#          default_prerelease_bump: ${{ steps.determine_bump.outputs.bump_type }}
#          append_to_pre_release_tag: pre
#          tag_prefix: v