name: Delivery

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --match "v[0-9]*-pre-[0-9]*" --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest=$latest_tag" >> $GITHUB_OUTPUT

      - name: Generate pre-release tag
        id: prerelease
        run: |
          base_version=$(echo "${{ steps.get_tag.outputs.latest }}" | sed 's/-.*//')
          prerelease_base="${base_version}-beta"
          existing=$(git tag --list "${prerelease_base}.*" | wc -l)
          new_tag="${prerelease_base}.$((existing + 1))"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

#      - name: Create pre-release tag
#        run: |
#          git tag "${{ steps.prerelease.outputs.new_tag }}"
#          git push origin "${{ steps.prerelease.outputs.new_tag }}"